@host=https://localhost:5234
@workspaceId=3458798c-c713-4a59-8b6f-99a48cfd05f4

PUT {{host}}/api/workspaces/{{workspaceId}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMGQ5MTMwMy1iNWM5LTQ1MzAtOTkxNC1kMjdjN2EwNTQ0MTUiLCJnaXZlbl9uYW1lIjoiSmFjdcWbIiwiZmFtaWx5X25hbWUiOiJCb3NhayIsImp0aSI6ImViOWIwYTE0LWU4NmItNGMwMi1iNzczLTYxZGYyMTgzYWZmOSIsImV4cCI6MTcyNTk4NTIyMCwiaXNzIjoiUGxhbkl0IiwiYXVkIjoiUGxhbkl0In0.Q61IfAqjyHhT9gL8IDHlM4Of_oDPXaB-l7Gwox-6Mw4

{
    "name": "Workspace 1 Edited",
    "description": "Workspace 1 description Edited"
}