@host=https://localhost:5234

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "asd",
    "lastName": "ddddd",
    "email": "kolos@email.com",
    "password": "haslo123"
}