@host=https://localhost:5234

POST {{host}}/api/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NDUxYTJjZS0zMzRkLTRmN2MtN2QzMy0wOGRjYzc2MmE5ZjEiLCJnaXZlbl9uYW1lIjoiRmlzdE5hbWUxIiwiZmFtaWx5X25hbWUiOiJMYXN0TmFtZTEiLCJqdGkiOiIxNzU5Y2UyOS02NGJlLTRhYTItOTQ5OC1kNTY3YTlmOGFiZjciLCJleHAiOjE3MjQ4NTc1MjAsImlzcyI6IlBsYW5JdCIsImF1ZCI6IlBsYW5JdCJ9.1LMnxWycAAH63Mx6acFND-tPjDl4ZuGDN68Uycu7Siw

{
    "name": "A new project",
    "description": "A project that will be perfect",
    "projectTasks": 
        [
            {
                "name": "Some task",
                "description": "Descirption of the task"
            },
            {
                "name": "Another task",
                "description": "Another description"
            }
        ]
}
