@host=https://localhost:5234
@projectOwnerId=94cacc8a-a08e-4b79-a728-58dd2884364a

POST {{host}}/projectOwners/{{projectOwnerId}}/project
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiYTNjZjVkMC1jYTg0LTQ3YzItOWI2MS1mNDA3NDFlOGQ4NmEiLCJnaXZlbl9uYW1lIjoiYXN4ZCIsImZhbWlseV9uYW1lIjoiZGRkZGQiLCJqdGkiOiIwY2JiNDBlOC05YWI2LTQ1MmQtOTZmMS1kOGE2Y2U0YTE2YjgiLCJleHAiOjE3MjQ3NDAzNTgsImlzcyI6IlBsYW5JdCIsImF1ZCI6IlBsYW5JdCJ9.e574dGTdxV9Byf8Uuasgs70_ufs1QcGraMcKppd-pEI

{
    "name": "Bolonez niemiecki",
    "description": "A project that will be perfect",
    "projectTasks": 
        [
            {
                "name": "Some task",
                "description": "Descirption of the task"
            },
            {
                "name": "Some task2",
                "description": "Descirption of the task2"
            }
        ]
}
