@host=https://localhost:5234
@projectId=b80011fd-f725-455d-9e45-e58fa76a3183

PUT {{host}}/api/projects/{{projectId}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NDUxYTJjZS0zMzRkLTRmN2MtN2QzMy0wOGRjYzc2MmE5ZjEiLCJnaXZlbl9uYW1lIjoiRmlzdE5hbWUxIiwiZmFtaWx5X25hbWUiOiJMYXN0TmFtZTEiLCJqdGkiOiI1YTU2NDM5Yy1kMDFlLTQ4MDAtYmJmYi0yOWE3YzFmY2MzMTMiLCJleHAiOjE3MjQ5MzEyOTQsImlzcyI6IlBsYW5JdCIsImF1ZCI6IlBsYW5JdCJ9.9M3QHT0aekoYZ7Ldqq7WmeZ4C_9nl0P-L_LQYVt5wgw

{
    "name": "Edited project 1 ",
    "description": "Edited project 1 description",
    "projectTasks": 
        [
            {
                "name": "Edited task 1",
                "description": "Edited task 1 description"
            },
            {
                "name": "Edited task 2",
                "description": "Edited task 2 description"
            }
        ]
}
