@host=https://localhost:5234
@projectId=a2a52276-dc54-4414-b654-299f8fb04f8d
@projectTaskId=522d237c-dc1a-4d8e-b055-defbbe43e063

POST {{host}}/api/projects/{{projectId}}/tasks/{{projectTaskId}}/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMGQ5MTMwMy1iNWM5LTQ1MzAtOTkxNC1kMjdjN2EwNTQ0MTUiLCJnaXZlbl9uYW1lIjoiSmFjdcWbIiwiZmFtaWx5X25hbWUiOiJCb3NhayIsImp0aSI6ImUxOWVmZGVhLWM5MTMtNDkwYi1hOTJhLTQ5NjcxNGIwOWViYSIsImV4cCI6MTcyNTQ2NDk4OSwiaXNzIjoiUGxhbkl0IiwiYXVkIjoiUGxhbkl0In0.uRjhYIGMRoe1L7nQGLxTaj1TE1aGpdJcTYtJAHIjxYk

{
    "name": "New Comment Title",
    "description": "New Comment Description"
}