@host=https://localhost:5234
@projectId=d0b41044-c9c0-40d3-9750-b1a72d4acbf4
@projectTaskId=79ac124a-f41f-4eae-a124-15bc33ca9d30

PUT {{host}}/api/projects/{{projectId}}/tasks/{{projectTaskId}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NDUxYTJjZS0zMzRkLTRmN2MtN2QzMy0wOGRjYzc2MmE5ZjEiLCJnaXZlbl9uYW1lIjoiRmlzdE5hbWUxIiwiZmFtaWx5X25hbWUiOiJMYXN0TmFtZTEiLCJqdGkiOiIyMDgxZGU1MS1hYjg4LTRlN2UtODIzZC1lZGYwYmRlNGQzZjIiLCJleHAiOjE3MjUwMDY1NzksImlzcyI6IlBsYW5JdCIsImF1ZCI6IlBsYW5JdCJ9.yKlnsdur9EuHNbEUxr0sW8cA482lhLDcgxCj3JVny04

{
    "name": "Edited Task",
    "description": "Edited Task description"
}