@host=https://localhost:5234

GET {{host}}/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTRjMTIzMC0wNWMxLTRmMGUtYTIzZS1lMGFiZjQ0NWU3NmQiLCJnaXZlbl9uYW1lIjoiYXN4ZCIsImZhbWlseV9uYW1lIjoiZGRkZGQiLCJqdGkiOiI1NTIyNGFkNS1mZWUwLTQ1OGYtYTc3Yy1hODkxMDlhOTY3ZjAiLCJleHAiOjE3MjQ0MTEzMDMsImlzcyI6IlBsYW5JdCIsImF1ZCI6IlBsYW5JdCJ9.Bs6XY__YXsJohquMdhemUry_2Xtx02K_iwYEdnVQuQQ